### ISSUE TITLE
Can't pick up money from the floor if you don't have space on the inventory

### ISSUE THREAD

**Issue by FunkyNico** [purevanillaco/Gemmy#3]
If you have the inventory full of items you can't pick up the money from the floor.

**Server:** Paper version git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Gemmy Version:** 2.3.1

Here is a video of the problem.
Hope you can fix it, thank you:D.

[gemmy.zip](https://github.com/purevanilla-es/Gemmy/files/4017121/gemmy.zip)

**Comment by quiquelhappy** [comment]
will take a look

**Comment by quiquelhappy** [comment]
added on the new release
