### ISSUE TITLE
Task #343 for GemsEconomy v4.8.3 generated an exception

### ISSUE THREAD

**Issue by FunkyNico** [purevanillaco/Gemmy#4]
**Server:** Paper version git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Gemmy:** v.2.3.1

**Error:** https://paste.ubuntu.com/p/mf2N9NdJ2G/

**Comment by quiquelhappy** [comment]
Hello, this has nothing to do with gemmy, this error is caused by gemseconomy and not gemmy
