### ISSUE TITLE
GEMMY AND MULTI-WORLDS

### ISSUE THREAD

**Issue by Rouxshi** [purevanillaco/Gemmy#5]
Hi there, 
I recently started using Gemmy, love the way it works in general but I couldn't find a way to limit o deactivate the function on specific word.

We have a specific world for mob arenas and other minigames, but is easy to grid gems in that way as all mobs drops gems evevn there.

Is possible to do something about it?

Paper 1.16.3
Gemmy 2.3.2

**Comment by quiquelhappy** [comment]
Will make sure to look into that option the next time I release an update (coming weeks)

**Comment by quiquelhappy** [comment]
added on the new release
