### ISSUE TITLE
1.18.1

### ISSUE THREAD

**Issue by Ofek270704** [purevanillaco/Gemmy#6]
Hello May you help me to solve a problem my server is on 1.18.1 and gemmy isnt working for my server how do i make it work.

26.02 02:16:19 [Server] INFO [Gemmy] Disabling Gemmy v2.4.5
26.02 02:16:19 [Server] ERROR Error occurred while disabling Gemmy v2.4.5 (Is it up to date?)

**Comment by quiquelhappy** [comment]
This is most likely because you are missing an economy plugin or vault.
Make sure vault is installed and you are using something such as EssentialsX, Gems Economy, TNE or any other economy provider of your choice — if this solved your issue please close this thread, else let me know :)

**Comment by Ofek270704** [comment]
those things are installed and updated

**Comment by Ofek270704** [comment]
it is working for lower versions

**Comment by Ofek270704** [comment]
?

**Comment by Ofek270704** [comment]
01.03 17:00:35 [Server] ERROR Error occurred while enabling Gemmy v2.4.5 (Is it up to date?)
01.03 17:00:35 [Server] INFO java.lang.IllegalArgumentException: No enum constant org.bukkit.Particle.SMALL_SMOKE
01.03 17:00:35 [Server] INFO at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
01.03 17:00:35 [Server] INFO at org.bukkit.Particle.valueOf(Particle.java:9) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
01.03 17:00:35 [Server] INFO at co.purevanilla.mcplugins.gemmy.util.Settings.<init>(Settings.java:263) ~[Gemmy (2).jar:?]
01.03 17:00:35 [Server] INFO at co.purevanilla.mcplugins.gemmy.Main.onEnable(Main.java:47) ~[Gemmy (2).jar:?]
01.03 17:00:35 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
01.03 17:00:35 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
01.03 17:00:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
01.03 17:00:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-"bfa50ad"]
01.03 17:00:35 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-"bfa50ad"]
01.03 17:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-"bfa50ad"]
01.03 17:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-"bfa50ad"]
01.03 17:00:35 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-"bfa50ad"]
01.03 17:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-"bfa50ad"]
01.03 17:00:35 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-"bfa50ad"]
01.03 17:00:35 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
01.03 17:00:35 [Server] INFO [Gemmy] Disabling Gemmy v2.4.5
